#!/usr/bin/env python3
"""Regenerate the Ukrainian white-paper portion of docs/index.html.

The landing page (docs/index.html) is hand-maintained for everything except the
rendered white paper, which is generated from the Markdown source so the two
never drift apart. Run this after editing ukrainian-latynytsia-v4.md:

    python tools/build-landing.py

Standard library only. Supports the Markdown subset the document actually uses:
ATX headings, paragraphs, ``**bold**`` / ``_italic_`` inline, GFM pipe tables,
thematic breaks, and backslash-escaped punctuation.
"""
from __future__ import annotations

import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "ukrainian-latynytsia-v4.md"
OUT = ROOT / "docs" / "index.html"

START = "<!-- DOC:START — generated by tools/build-landing.py, do not edit by hand -->"
END = "<!-- DOC:END -->"

_ESCAPE_RE = re.compile(r"\\([\\`*_{}\[\]()#+.!>~|-])")
_BOLD_RE = re.compile(r"\*\*(?!\s)(.+?)(?<!\s)\*\*")
_ITALIC_RE = re.compile(r"(?<![\w*])_(?!\s)(.+?)(?<!\s)_(?![\w])")
_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$")
_HR_RE = re.compile(r"^\s*([-*_])(?:\s*\1){2,}\s*$")
_SEP_RE = re.compile(r"^\s*\|?[\s:|-]*-[\s:|-]*\|?\s*$")


def _unescape(text: str) -> str:
    return _ESCAPE_RE.sub(r"\1", text)


def inline(text: str) -> str:
    """Render inline markup. HTML-escapes first, then applies markup."""
    text = html.escape(text, quote=False)
    text = _BOLD_RE.sub(r"<strong>\1</strong>", text)
    text = _ITALIC_RE.sub(r"<em>\1</em>", text)
    return _unescape(text)


def _split_row(row: str) -> list[str]:
    row = row.strip()
    if row.startswith("|"):
        row = row[1:]
    if row.endswith("|"):
        row = row[:-1]
    return [cell.strip() for cell in row.split("|")]


def _render_table(header: list[str], rows: list[list[str]]) -> str:
    width = len(header)
    head_cells = "".join(f"<th>{inline(c)}</th>" for c in header)
    body_rows = []
    for row in rows:
        cells = (row + [""] * width)[:width]
        body_rows.append("<tr>" + "".join(f"<td>{inline(c)}</td>" for c in cells) + "</tr>")
    return (
        '<div class="table-wrap"><table>\n'
        f"<thead><tr>{head_cells}</tr></thead>\n"
        "<tbody>\n" + "\n".join(body_rows) + "\n</tbody>\n"
        "</table></div>"
    )


def convert(md: str, *, skip_leading_h1: bool = True, demote: int = 1) -> str:
    lines = md.replace("\r\n", "\n").split("\n")
    out: list[str] = []
    para: list[str] = []
    i, n = 0, len(lines)
    skipped_h1 = not skip_leading_h1

    def flush() -> None:
        if para:
            joined = " ".join(p.strip() for p in para).strip()
            if joined:
                out.append(f"<p>{inline(joined)}</p>")
            para.clear()

    while i < n:
        line = lines[i]
        stripped = line.strip()

        heading = _HEADING_RE.match(line)
        if heading:
            flush()
            level = len(heading.group(1))
            body = heading.group(2).strip()
            if not skipped_h1 and level == 1:
                skipped_h1 = True
                i += 1
                continue
            level = min(level + demote, 6)
            out.append(f"<h{level}>{inline(body)}</h{level}>")
            i += 1
            continue

        if _HR_RE.match(stripped):
            flush()
            out.append("<hr>")
            i += 1
            continue

        if (
            stripped.startswith("|")
            and i + 1 < n
            and _SEP_RE.match(lines[i + 1])
        ):
            flush()
            header = _split_row(stripped)
            i += 2
            rows = []
            while i < n and lines[i].strip().startswith("|"):
                rows.append(_split_row(lines[i]))
                i += 1
            out.append(_render_table(header, rows))
            continue

        if stripped == "":
            flush()
            i += 1
            continue

        para.append(line)
        i += 1

    flush()
    return "\n".join(out)


def main() -> int:
    if not SRC.exists():
        sys.exit(f"source not found: {SRC}")
    if not OUT.exists():
        sys.exit(f"target not found: {OUT}")

    fragment = convert(SRC.read_text(encoding="utf-8"))
    page = OUT.read_text(encoding="utf-8")

    block = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    new_page, count = block.subn(
        lambda _m: f"{START}\n{fragment}\n{END}", page, count=1
    )
    if count != 1:
        sys.exit(
            f"expected exactly one DOC block between markers, found {count}. "
            "Check docs/index.html."
        )

    OUT.write_text(new_page, encoding="utf-8", newline="\n")
    print(f"OK: injected {len(fragment):,} chars of HTML into {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
